import {
  mkdir,
  mkdtemp,
  readFile,
  realpath,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { createProjectOutputWriter } from "../src/project-output.js";

const temporaryDirectories: string[] = [];
let projectRoot: string;

async function createTemporaryDirectory(prefix: string): Promise<string> {
  const directory = await mkdtemp(path.join(tmpdir(), prefix));
  temporaryDirectories.push(directory);
  return directory;
}

async function removeTemporaryDirectory(directory: string): Promise<void> {
  const relative = path.relative(tmpdir(), directory);
  if (
    relative === "" ||
    relative === ".." ||
    relative.startsWith(`..${path.sep}`) ||
    path.isAbsolute(relative)
  ) {
    throw new Error(`Refusing to remove non-temporary path: ${directory}`);
  }
  await rm(directory, { recursive: true, force: true });
}

beforeEach(async () => {
  projectRoot = await createTemporaryDirectory("deck-output-project-");
  await writeFile(path.join(projectRoot, ".deck-project"), "", "utf8");
});

afterEach(async () => {
  const directories = temporaryDirectories.splice(0);
  await Promise.all(directories.map(removeTemporaryDirectory));
});

describe("createProjectOutputWriter", () => {
  it("writes generated bytes inside output/ through the workspace guard", async () => {
    const writer = createProjectOutputWriter(projectRoot);
    const data = new Uint8Array([80, 75, 3, 4]);

    const result = await writer.write("output/deck.pptx", data);

    expect(result).toEqual({
      relativePath: "output/deck.pptx",
      absolutePath: path.join(
        await realpath(projectRoot),
        "output",
        "deck.pptx",
      ),
      bytesWritten: data.byteLength,
    });
    expect(await readFile(result.absolutePath)).toEqual(Buffer.from(data));
  });

  it("rejects writes outside output/", async () => {
    const writer = createProjectOutputWriter(projectRoot);

    for (const outputPath of [
      "pages/deck.pptx",
      "output",
      String.raw`output\deck.pptx`,
    ]) {
      await expect(
        writer.write(outputPath, new Uint8Array()),
      ).rejects.toMatchObject({ code: "OUTPUT_PATH_INVALID" });
    }
  });

  it("requires the project marker", async () => {
    await rm(path.join(projectRoot, ".deck-project"));
    const writer = createProjectOutputWriter(projectRoot);

    await expect(
      writer.write("output/deck.pptx", new Uint8Array()),
    ).rejects.toMatchObject({ code: "PROJECT_MARKER_MISSING" });
  });

  it("rejects an output directory symlink escape", async () => {
    const outsideRoot = await createTemporaryDirectory("deck-output-outside-");
    await mkdir(outsideRoot, { recursive: true });
    await symlink(outsideRoot, path.join(projectRoot, "output"), "dir");
    const writer = createProjectOutputWriter(projectRoot);

    await expect(
      writer.write("output/deck.pptx", new Uint8Array()),
    ).rejects.toMatchObject({ code: "SYMLINK_ESCAPE" });
  });
});
