import {
  mkdir,
  mkdtemp,
  readFile,
  realpath,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { createProjectPreviewWriter } from "../src/project-preview.js";

const temporaryDirectories: string[] = [];
let projectRoot: string;

async function createTemporaryDirectory(prefix: string): Promise<string> {
  const directory = await mkdtemp(path.join(tmpdir(), prefix));
  temporaryDirectories.push(directory);
  return directory;
}

async function removeTemporaryDirectory(directory: string): Promise<void> {
  const relative = path.relative(tmpdir(), directory);
  if (
    relative === "" ||
    relative === ".." ||
    relative.startsWith(`..${path.sep}`) ||
    path.isAbsolute(relative)
  ) {
    throw new Error(`Refusing to remove non-temporary path: ${directory}`);
  }
  await rm(directory, { recursive: true, force: true });
}

beforeEach(async () => {
  projectRoot = await createTemporaryDirectory("deck-preview-project-");
  await writeFile(path.join(projectRoot, ".deck-project"), "", "utf8");
});

afterEach(async () => {
  const directories = temporaryDirectories.splice(0);
  await Promise.all(directories.map(removeTemporaryDirectory));
});

describe("createProjectPreviewWriter", () => {
  it("writes generated bytes inside preview/ through the workspace guard", async () => {
    const writer = createProjectPreviewWriter(projectRoot);
    const data = new Uint8Array([137, 80, 78, 71]);

    const result = await writer.write("preview/01.png", data);

    expect(result).toEqual({
      relativePath: "preview/01.png",
      absolutePath: path.join(await realpath(projectRoot), "preview", "01.png"),
      bytesWritten: data.byteLength,
    });
    expect(await readFile(result.absolutePath)).toEqual(Buffer.from(data));
  });

  it("rejects writes outside preview/", async () => {
    const writer = createProjectPreviewWriter(projectRoot);

    for (const previewPath of [
      "output/01.png",
      "preview",
      String.raw`preview\01.png`,
      "preview/../output/01.png",
    ]) {
      await expect(
        writer.write(previewPath, new Uint8Array()),
      ).rejects.toMatchObject({
        code:
          previewPath === "preview/../output/01.png"
            ? "PATH_TRAVERSAL"
            : "PREVIEW_PATH_INVALID",
      });
    }
  });

  it("requires the project marker", async () => {
    await rm(path.join(projectRoot, ".deck-project"));
    const writer = createProjectPreviewWriter(projectRoot);

    await expect(
      writer.write("preview/01.png", new Uint8Array()),
    ).rejects.toMatchObject({ code: "PROJECT_MARKER_MISSING" });
  });

  it("rejects a preview directory symlink escape", async () => {
    const outsideRoot = await createTemporaryDirectory("deck-preview-outside-");
    await mkdir(outsideRoot, { recursive: true });
    await symlink(outsideRoot, path.join(projectRoot, "preview"), "dir");
    const writer = createProjectPreviewWriter(projectRoot);

    await expect(
      writer.write("preview/01.png", new Uint8Array()),
    ).rejects.toMatchObject({ code: "SYMLINK_ESCAPE" });
  });
});
